- fix cannot convert argument 2 from 'const char [N]' to 'char *' - fix warning C5033: 'register' is no longer a supported storage class - fix warning C4477: 'fprintf' : format string '%x' requires an argument of type 'unsigned int', but variadic argument 1 has type '_nfa_node *' - fix error C2440: 'initializing': cannot convert from 'const char [N]' to 'char *' - fix warning C4255: 'GenCPPClassCode': no function prototype given: converting '()' to '(void)'